---
name: Reusable workflow for Docker Build

on:
  workflow_call:
    inputs:
      app:
        description: "App name for matrix builds"
        required: false
        type: string
      dockerfile:
        description: "Path to the Dockerfile"
        default: "Dockerfile"
        required: false
        type: string
      version:
        description: "Version tag of docker build"
        required: false
        type: string

jobs:
  docker:
    name: Docker Build Push
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
             # $app-latest if inputs.app is defined, otherwise just latest
             ${{ inputs.app && format('type=raw,value={0}-latest', inputs.app) || 'type=raw,value=latest' }}

             # $app-$version if inputs.app and inputs.version are defined
             ${{ inputs.app && inputs.version && format('type=raw,value={0}-{1}', inputs.app, inputs.version) }}

             # $version if inputs.app is not defined and inputs.version is defined
             ${{ !inputs.app && inputs.version && format('type=raw,value={0}', inputs.version) || '' }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ${{ inputs.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: false
